
so ~/.vim/general.vim
so ~/.vim/bundles.vim
so ~/.vim/shortcuts.vim
so ~/.vim/extra.vim

"colorscheme peachpuff
colorscheme molokai
"colorscheme one
"set background=dark

set guicursor+=a:blinkon0

" NOTES
" :set ft=ruby to force the syntax coloration

" au WinLeave * set nocursorline nocursorcolumn
" au WinEnter * set cursorline
" set cursorline

